import * as test_0 from './src/testsAutoImporter/writeFile/writeFile.test.js'
import * as test_1 from './src/testsAutoImporter/scanDirectoryTree/scanDirectoryTree.test.js'
import * as test_2 from './src/testsAutoImporter/readFile/readFile.test.js'
import * as test_3 from './src/testsAutoImporter/utils/arrays/strings/createImportsFromPaths/createImportsFromPaths.test.js'
import * as test_4 from './src/testsAutoImporter/utils/arrays/strings/createImportsExportsFromPaths/createImportsExportsFromPaths.test.js'
import * as test_5 from './src/testsAutoImporter/utils/arrays/strings/createImportNamesFromArrayIndexes/createImportNamesFromArrayIndexes.test.js'
import * as test_6 from './src/testsAutoImporter/utils/arrays/strings/createExportsFromArray/createExportsFromArray.test.js'
import * as test_7 from './src/testsAutoImporter/testingLibrary/utils/string/splitBySubstring/splitBySubstring.test.js'
import * as test_8 from './src/testsAutoImporter/testingLibrary/utils/string/removeTimeInfo/removeTimeInfo.test.js'
import * as test_9 from './src/testsAutoImporter/testingLibrary/utils/string/beautifyTestsLog/beautifyTestsLog.test.js'
export const tests = {...test_0,...test_1,...test_2,...test_3,...test_4,...test_5,...test_6,...test_7,...test_8,...test_9}